#if 0
#elif defined(__arm64__) && __arm64__
// Generated by Apple Swift version 5.8.1 (swiftlang-5.8.0.124.5 clang-1403.0.22.11.100)
#ifndef ARKNFC_SWIFT_H
#define ARKNFC_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#if defined(__OBJC__)
#include <Foundation/Foundation.h>
#endif
#if defined(__cplusplus)
#include <cstdint>
#include <cstddef>
#include <cstdbool>
#include <cstring>
#include <stdlib.h>
#include <new>
#include <type_traits>
#else
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include <string.h>
#endif
#if defined(__cplusplus)
#if __has_include(<ptrauth.h>)
# include <ptrauth.h>
#else
# ifndef __ptrauth_swift_value_witness_function_pointer
#  define __ptrauth_swift_value_witness_function_pointer(x)
# endif
#endif
#endif

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...) 
# endif
#endif
#if !defined(SWIFT_RUNTIME_NAME)
# if __has_attribute(objc_runtime_name)
#  define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
# else
#  define SWIFT_RUNTIME_NAME(X) 
# endif
#endif
#if !defined(SWIFT_COMPILE_NAME)
# if __has_attribute(swift_name)
#  define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
# else
#  define SWIFT_COMPILE_NAME(X) 
# endif
#endif
#if !defined(SWIFT_METHOD_FAMILY)
# if __has_attribute(objc_method_family)
#  define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
# else
#  define SWIFT_METHOD_FAMILY(X) 
# endif
#endif
#if !defined(SWIFT_NOESCAPE)
# if __has_attribute(noescape)
#  define SWIFT_NOESCAPE __attribute__((noescape))
# else
#  define SWIFT_NOESCAPE 
# endif
#endif
#if !defined(SWIFT_RELEASES_ARGUMENT)
# if __has_attribute(ns_consumed)
#  define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
# else
#  define SWIFT_RELEASES_ARGUMENT 
# endif
#endif
#if !defined(SWIFT_WARN_UNUSED_RESULT)
# if __has_attribute(warn_unused_result)
#  define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
# else
#  define SWIFT_WARN_UNUSED_RESULT 
# endif
#endif
#if !defined(SWIFT_NORETURN)
# if __has_attribute(noreturn)
#  define SWIFT_NORETURN __attribute__((noreturn))
# else
#  define SWIFT_NORETURN 
# endif
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA 
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA 
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA 
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif
#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif
#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER 
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility) 
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED_OBJC)
# if __has_feature(attribute_diagnose_if_objc)
#  define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
# else
#  define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
# endif
#endif
#if defined(__OBJC__)
#if !defined(IBSegueAction)
# define IBSegueAction 
#endif
#endif
#if !defined(SWIFT_EXTERN)
# if defined(__cplusplus)
#  define SWIFT_EXTERN extern "C"
# else
#  define SWIFT_EXTERN extern
# endif
#endif
#if !defined(SWIFT_CALL)
# define SWIFT_CALL __attribute__((swiftcall))
#endif
#if !defined(SWIFT_INDIRECT_RESULT)
# define SWIFT_INDIRECT_RESULT __attribute__((swift_indirect_result))
#endif
#if !defined(SWIFT_CONTEXT)
# define SWIFT_CONTEXT __attribute__((swift_context))
#endif
#if !defined(SWIFT_ERROR_RESULT)
# define SWIFT_ERROR_RESULT __attribute__((swift_error_result))
#endif
#if defined(__cplusplus)
# define SWIFT_NOEXCEPT noexcept
#else
# define SWIFT_NOEXCEPT 
#endif
#if defined(_WIN32)
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL __declspec(dllimport)
#endif
#else
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL 
#endif
#endif
#if defined(__OBJC__)
#if __has_feature(objc_modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import CoreFoundation;
@import Foundation;
@import ObjectiveC;
@import UIKit;
#endif

#endif
#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="ArkNFC",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__OBJC__)
@protocol ArkPspNfcDataReaderDelegate;
@class NSString;
@class NSCoder;

SWIFT_CLASS("_TtC6ArkNFC19ArkPspNfcDataReader") SWIFT_AVAILABILITY(ios,introduced=13.0)
@interface ArkPspNfcDataReader : UIView
@property (nonatomic, weak) id <ArkPspNfcDataReaderDelegate> _Nullable delegate;
@property (nonatomic) NSInteger timeoutDurationInMillisecond;
@property (nonatomic, copy) NSString * _Nullable mrzString;
@property (nonatomic, copy) NSString * _Nonnull msgPlaceCardPrompt;
@property (nonatomic, copy) NSString * _Nonnull msgReadingData;
@property (nonatomic, copy) NSString * _Nonnull msgReadingDone;
@property (nonatomic, copy) NSString * _Nonnull msgReadingError;
@property (nonatomic, copy) NSString * _Nonnull msgProgressFilled;
@property (nonatomic, copy) NSString * _Nonnull msgProgressEmpty;
- (void)drawRect:(CGRect)rect;
- (void)start;
- (void)stop;
- (NSString * _Nonnull)getActiveAuthChallenge SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nonnull)getActiveAuthSignature SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nullable)getCompressedPhotoDataBase64:(NSInteger)jpegQuality SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end



SWIFT_PROTOCOL("_TtP6ArkNFC27ArkPspNfcDataReaderDelegate_") SWIFT_AVAILABILITY(ios,introduced=13.0)
@protocol ArkPspNfcDataReaderDelegate
- (void)onDataGroupReadWithDgNumber:(NSInteger)dgNumber totalNumberOfDgs:(NSInteger)totalNumberOfDgs;
- (void)onNfcReadTimeout;
- (void)onNfcReadFailedWithStatusCode:(NSInteger)statusCode;
- (void)onNfcReadSuccessfully;
@end


SWIFT_CLASS("_TtC6ArkNFC12ArkPspReader") SWIFT_AVAILABILITY(ios,introduced=13)
@interface ArkPspReader : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end



@protocol ArkTckkNfcDataReaderDelegate;
@class UIImage;
@class NSDate;
@class NSNumber;

SWIFT_CLASS("_TtC6ArkNFC20ArkTckkNfcDataReader") SWIFT_AVAILABILITY(ios,introduced=13.0)
@interface ArkTckkNfcDataReader : UIView
@property (nonatomic, weak) id <ArkTckkNfcDataReaderDelegate> _Nullable delegate;
@property (nonatomic) NSInteger timeoutDurationInMillisecond;
@property (nonatomic, copy) NSString * _Nullable mrzString;
@property (nonatomic, copy) NSArray<NSNumber *> * _Nonnull challange;
@property (nonatomic, copy) NSString * _Nonnull msgPlaceCardPrompt;
@property (nonatomic, copy) NSString * _Nonnull msgReadingData;
@property (nonatomic, copy) NSString * _Nonnull msgReadingDone;
@property (nonatomic, copy) NSString * _Nonnull msgReadingError;
@property (nonatomic, copy) NSString * _Nonnull msgProgressFilled;
@property (nonatomic, copy) NSString * _Nonnull msgProgressEmpty;
- (void)start;
- (void)stop;
- (UIImage * _Nullable)getPhotoData SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nullable)getCompressedPhotoDataBase64:(NSInteger)jpegQuality SWIFT_WARN_UNUSED_RESULT;
- (UIImage * _Nullable)getCompressedPhotoData:(NSInteger)jpegQuality SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nullable)getPhotoDataBase64 SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nullable)getFullName SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nullable)getNfcTckn SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nullable)getNfcPlaceOfBirth SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nullable)getNfcGender SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nullable)getNfcFullName SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nullable)getFirstName SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nullable)getLastName SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nullable)getDocumentSerialNumber SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nullable)getDateOfBirth SWIFT_WARN_UNUSED_RESULT;
- (NSDate * _Nullable)getDateOfBirthAsDate SWIFT_WARN_UNUSED_RESULT;
- (NSNumber * _Nullable)getAge SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nullable)getDateOfExpiration SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nullable)getNationality SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nonnull)getDg1Base64 SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nonnull)getDg2Base64 SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nonnull)getDg3Base64 SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nonnull)getDg4Base64 SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nonnull)getDg5Base64 SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nonnull)getDg6Base64 SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nonnull)getDg7Base64 SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nonnull)getDg8Base64 SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nonnull)getDg9Base64 SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nonnull)getDg10Base64 SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nonnull)getDg11Base64 SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nonnull)getDg12Base64 SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nonnull)getDg13Base64 SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nonnull)getDg14Base64 SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nonnull)getDg15Base64 SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nonnull)getDg16Base64 SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nonnull)getEfSodBase64 SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nonnull)getEfComBase64 SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nonnull)getActiveAuthChallenge SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nonnull)getActiveAuthSignature SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end



SWIFT_PROTOCOL("_TtP6ArkNFC28ArkTckkNfcDataReaderDelegate_") SWIFT_AVAILABILITY(ios,introduced=13.0)
@protocol ArkTckkNfcDataReaderDelegate
- (void)onDataGroupReadWithDgNumber:(NSInteger)dgNumber totalNumberOfDgs:(NSInteger)totalNumberOfDgs;
- (void)onNfcReadTimeout;
- (void)onNfcReadFailedWithStatusCode:(NSInteger)statusCode;
- (void)onNfcReadSuccessfully;
@end


SWIFT_CLASS("_TtC6ArkNFC13ArkTckkReader") SWIFT_AVAILABILITY(ios,introduced=13)
@interface ArkTckkReader : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end





SWIFT_CLASS("_TtC6ArkNFC11LiveAuthLog")
@interface LiveAuthLog : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC6ArkNFC12NfcErrorCode")
@interface NfcErrorCode : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger UNKNOWN;)
+ (NSInteger)UNKNOWN SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger ERROR_NFC_READ_FAILED;)
+ (NSInteger)ERROR_NFC_READ_FAILED SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger ERROR_WRONG_PARAMETER_ENCODED_MRZ_STRING;)
+ (NSInteger)ERROR_WRONG_PARAMETER_ENCODED_MRZ_STRING SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger DEVICE_NOT_HAVE_NFC_FEATURE;)
+ (NSInteger)DEVICE_NOT_HAVE_NFC_FEATURE SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger ERROR_NFC_TAG_NOT_SUPPORT_ISO_DEP;)
+ (NSInteger)ERROR_NFC_TAG_NOT_SUPPORT_ISO_DEP SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger ERROR_CANT_CONNECT_NFC_TAG;)
+ (NSInteger)ERROR_CANT_CONNECT_NFC_TAG SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger ERROR_NFC_TAG_NOT_SUPPORTED;)
+ (NSInteger)ERROR_NFC_TAG_NOT_SUPPORTED SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger ERROR_NFC_TAG_LOST;)
+ (NSInteger)ERROR_NFC_TAG_LOST SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger ERROR_EXTERNAL_AUTH_FAILED;)
+ (NSInteger)ERROR_EXTERNAL_AUTH_FAILED SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger ERROR_NFC_DISABLED;)
+ (NSInteger)ERROR_NFC_DISABLED SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger ERROR_USER_CANCELED;)
+ (NSInteger)ERROR_USER_CANCELED SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger ERROR_MORE_THAN_ONE_TAG_FOUND;)
+ (NSInteger)ERROR_MORE_THAN_ONE_TAG_FOUND SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger ERROR_IDCARD_CAN_NOT_IDENTIFY;)
+ (NSInteger)ERROR_IDCARD_CAN_NOT_IDENTIFY SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC6ArkNFC18NfcErrorCodeHelper")
@interface NfcErrorCodeHelper : NSObject
+ (NSString * _Nonnull)toStringWithVal:(NSInteger)val SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

#endif
#if defined(__cplusplus)
#endif
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#pragma clang diagnostic pop
#endif

#elif defined(__x86_64__) && __x86_64__
// Generated by Apple Swift version 5.8.1 (swiftlang-5.8.0.124.5 clang-1403.0.22.11.100)
#ifndef ARKNFC_SWIFT_H
#define ARKNFC_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#if defined(__OBJC__)
#include <Foundation/Foundation.h>
#endif
#if defined(__cplusplus)
#include <cstdint>
#include <cstddef>
#include <cstdbool>
#include <cstring>
#include <stdlib.h>
#include <new>
#include <type_traits>
#else
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include <string.h>
#endif
#if defined(__cplusplus)
#if __has_include(<ptrauth.h>)
# include <ptrauth.h>
#else
# ifndef __ptrauth_swift_value_witness_function_pointer
#  define __ptrauth_swift_value_witness_function_pointer(x)
# endif
#endif
#endif

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...) 
# endif
#endif
#if !defined(SWIFT_RUNTIME_NAME)
# if __has_attribute(objc_runtime_name)
#  define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
# else
#  define SWIFT_RUNTIME_NAME(X) 
# endif
#endif
#if !defined(SWIFT_COMPILE_NAME)
# if __has_attribute(swift_name)
#  define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
# else
#  define SWIFT_COMPILE_NAME(X) 
# endif
#endif
#if !defined(SWIFT_METHOD_FAMILY)
# if __has_attribute(objc_method_family)
#  define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
# else
#  define SWIFT_METHOD_FAMILY(X) 
# endif
#endif
#if !defined(SWIFT_NOESCAPE)
# if __has_attribute(noescape)
#  define SWIFT_NOESCAPE __attribute__((noescape))
# else
#  define SWIFT_NOESCAPE 
# endif
#endif
#if !defined(SWIFT_RELEASES_ARGUMENT)
# if __has_attribute(ns_consumed)
#  define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
# else
#  define SWIFT_RELEASES_ARGUMENT 
# endif
#endif
#if !defined(SWIFT_WARN_UNUSED_RESULT)
# if __has_attribute(warn_unused_result)
#  define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
# else
#  define SWIFT_WARN_UNUSED_RESULT 
# endif
#endif
#if !defined(SWIFT_NORETURN)
# if __has_attribute(noreturn)
#  define SWIFT_NORETURN __attribute__((noreturn))
# else
#  define SWIFT_NORETURN 
# endif
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA 
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA 
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA 
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif
#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif
#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER 
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility) 
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED_OBJC)
# if __has_feature(attribute_diagnose_if_objc)
#  define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
# else
#  define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
# endif
#endif
#if defined(__OBJC__)
#if !defined(IBSegueAction)
# define IBSegueAction 
#endif
#endif
#if !defined(SWIFT_EXTERN)
# if defined(__cplusplus)
#  define SWIFT_EXTERN extern "C"
# else
#  define SWIFT_EXTERN extern
# endif
#endif
#if !defined(SWIFT_CALL)
# define SWIFT_CALL __attribute__((swiftcall))
#endif
#if !defined(SWIFT_INDIRECT_RESULT)
# define SWIFT_INDIRECT_RESULT __attribute__((swift_indirect_result))
#endif
#if !defined(SWIFT_CONTEXT)
# define SWIFT_CONTEXT __attribute__((swift_context))
#endif
#if !defined(SWIFT_ERROR_RESULT)
# define SWIFT_ERROR_RESULT __attribute__((swift_error_result))
#endif
#if defined(__cplusplus)
# define SWIFT_NOEXCEPT noexcept
#else
# define SWIFT_NOEXCEPT 
#endif
#if defined(_WIN32)
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL __declspec(dllimport)
#endif
#else
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL 
#endif
#endif
#if defined(__OBJC__)
#if __has_feature(objc_modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import CoreFoundation;
@import Foundation;
@import ObjectiveC;
@import UIKit;
#endif

#endif
#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="ArkNFC",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__OBJC__)
@protocol ArkPspNfcDataReaderDelegate;
@class NSString;
@class NSCoder;

SWIFT_CLASS("_TtC6ArkNFC19ArkPspNfcDataReader") SWIFT_AVAILABILITY(ios,introduced=13.0)
@interface ArkPspNfcDataReader : UIView
@property (nonatomic, weak) id <ArkPspNfcDataReaderDelegate> _Nullable delegate;
@property (nonatomic) NSInteger timeoutDurationInMillisecond;
@property (nonatomic, copy) NSString * _Nullable mrzString;
@property (nonatomic, copy) NSString * _Nonnull msgPlaceCardPrompt;
@property (nonatomic, copy) NSString * _Nonnull msgReadingData;
@property (nonatomic, copy) NSString * _Nonnull msgReadingDone;
@property (nonatomic, copy) NSString * _Nonnull msgReadingError;
@property (nonatomic, copy) NSString * _Nonnull msgProgressFilled;
@property (nonatomic, copy) NSString * _Nonnull msgProgressEmpty;
- (void)drawRect:(CGRect)rect;
- (void)start;
- (void)stop;
- (NSString * _Nonnull)getActiveAuthChallenge SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nonnull)getActiveAuthSignature SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nullable)getCompressedPhotoDataBase64:(NSInteger)jpegQuality SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end



SWIFT_PROTOCOL("_TtP6ArkNFC27ArkPspNfcDataReaderDelegate_") SWIFT_AVAILABILITY(ios,introduced=13.0)
@protocol ArkPspNfcDataReaderDelegate
- (void)onDataGroupReadWithDgNumber:(NSInteger)dgNumber totalNumberOfDgs:(NSInteger)totalNumberOfDgs;
- (void)onNfcReadTimeout;
- (void)onNfcReadFailedWithStatusCode:(NSInteger)statusCode;
- (void)onNfcReadSuccessfully;
@end


SWIFT_CLASS("_TtC6ArkNFC12ArkPspReader") SWIFT_AVAILABILITY(ios,introduced=13)
@interface ArkPspReader : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end



@protocol ArkTckkNfcDataReaderDelegate;
@class UIImage;
@class NSDate;
@class NSNumber;

SWIFT_CLASS("_TtC6ArkNFC20ArkTckkNfcDataReader") SWIFT_AVAILABILITY(ios,introduced=13.0)
@interface ArkTckkNfcDataReader : UIView
@property (nonatomic, weak) id <ArkTckkNfcDataReaderDelegate> _Nullable delegate;
@property (nonatomic) NSInteger timeoutDurationInMillisecond;
@property (nonatomic, copy) NSString * _Nullable mrzString;
@property (nonatomic, copy) NSArray<NSNumber *> * _Nonnull challange;
@property (nonatomic, copy) NSString * _Nonnull msgPlaceCardPrompt;
@property (nonatomic, copy) NSString * _Nonnull msgReadingData;
@property (nonatomic, copy) NSString * _Nonnull msgReadingDone;
@property (nonatomic, copy) NSString * _Nonnull msgReadingError;
@property (nonatomic, copy) NSString * _Nonnull msgProgressFilled;
@property (nonatomic, copy) NSString * _Nonnull msgProgressEmpty;
- (void)start;
- (void)stop;
- (UIImage * _Nullable)getPhotoData SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nullable)getCompressedPhotoDataBase64:(NSInteger)jpegQuality SWIFT_WARN_UNUSED_RESULT;
- (UIImage * _Nullable)getCompressedPhotoData:(NSInteger)jpegQuality SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nullable)getPhotoDataBase64 SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nullable)getFullName SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nullable)getNfcTckn SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nullable)getNfcPlaceOfBirth SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nullable)getNfcGender SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nullable)getNfcFullName SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nullable)getFirstName SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nullable)getLastName SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nullable)getDocumentSerialNumber SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nullable)getDateOfBirth SWIFT_WARN_UNUSED_RESULT;
- (NSDate * _Nullable)getDateOfBirthAsDate SWIFT_WARN_UNUSED_RESULT;
- (NSNumber * _Nullable)getAge SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nullable)getDateOfExpiration SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nullable)getNationality SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nonnull)getDg1Base64 SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nonnull)getDg2Base64 SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nonnull)getDg3Base64 SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nonnull)getDg4Base64 SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nonnull)getDg5Base64 SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nonnull)getDg6Base64 SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nonnull)getDg7Base64 SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nonnull)getDg8Base64 SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nonnull)getDg9Base64 SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nonnull)getDg10Base64 SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nonnull)getDg11Base64 SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nonnull)getDg12Base64 SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nonnull)getDg13Base64 SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nonnull)getDg14Base64 SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nonnull)getDg15Base64 SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nonnull)getDg16Base64 SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nonnull)getEfSodBase64 SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nonnull)getEfComBase64 SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nonnull)getActiveAuthChallenge SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nonnull)getActiveAuthSignature SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end



SWIFT_PROTOCOL("_TtP6ArkNFC28ArkTckkNfcDataReaderDelegate_") SWIFT_AVAILABILITY(ios,introduced=13.0)
@protocol ArkTckkNfcDataReaderDelegate
- (void)onDataGroupReadWithDgNumber:(NSInteger)dgNumber totalNumberOfDgs:(NSInteger)totalNumberOfDgs;
- (void)onNfcReadTimeout;
- (void)onNfcReadFailedWithStatusCode:(NSInteger)statusCode;
- (void)onNfcReadSuccessfully;
@end


SWIFT_CLASS("_TtC6ArkNFC13ArkTckkReader") SWIFT_AVAILABILITY(ios,introduced=13)
@interface ArkTckkReader : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end





SWIFT_CLASS("_TtC6ArkNFC11LiveAuthLog")
@interface LiveAuthLog : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC6ArkNFC12NfcErrorCode")
@interface NfcErrorCode : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger UNKNOWN;)
+ (NSInteger)UNKNOWN SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger ERROR_NFC_READ_FAILED;)
+ (NSInteger)ERROR_NFC_READ_FAILED SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger ERROR_WRONG_PARAMETER_ENCODED_MRZ_STRING;)
+ (NSInteger)ERROR_WRONG_PARAMETER_ENCODED_MRZ_STRING SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger DEVICE_NOT_HAVE_NFC_FEATURE;)
+ (NSInteger)DEVICE_NOT_HAVE_NFC_FEATURE SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger ERROR_NFC_TAG_NOT_SUPPORT_ISO_DEP;)
+ (NSInteger)ERROR_NFC_TAG_NOT_SUPPORT_ISO_DEP SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger ERROR_CANT_CONNECT_NFC_TAG;)
+ (NSInteger)ERROR_CANT_CONNECT_NFC_TAG SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger ERROR_NFC_TAG_NOT_SUPPORTED;)
+ (NSInteger)ERROR_NFC_TAG_NOT_SUPPORTED SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger ERROR_NFC_TAG_LOST;)
+ (NSInteger)ERROR_NFC_TAG_LOST SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger ERROR_EXTERNAL_AUTH_FAILED;)
+ (NSInteger)ERROR_EXTERNAL_AUTH_FAILED SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger ERROR_NFC_DISABLED;)
+ (NSInteger)ERROR_NFC_DISABLED SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger ERROR_USER_CANCELED;)
+ (NSInteger)ERROR_USER_CANCELED SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger ERROR_MORE_THAN_ONE_TAG_FOUND;)
+ (NSInteger)ERROR_MORE_THAN_ONE_TAG_FOUND SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger ERROR_IDCARD_CAN_NOT_IDENTIFY;)
+ (NSInteger)ERROR_IDCARD_CAN_NOT_IDENTIFY SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC6ArkNFC18NfcErrorCodeHelper")
@interface NfcErrorCodeHelper : NSObject
+ (NSString * _Nonnull)toStringWithVal:(NSInteger)val SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

#endif
#if defined(__cplusplus)
#endif
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#pragma clang diagnostic pop
#endif

#else
#error unsupported Swift architecture
#endif
